language: cpp
sudo: required
dist: trusty

env:
  matrix:
    - TEST_WITH_MA27=0 OPENMPI=1 MPICH=0
    - TEST_WITH_MA27=1 OPENMPI=1 MPICH=0
    - TEST_WITH_MA27=0 OPENMPI=0 MPICH=1
    - TEST_WITH_MA27=1 OPENMPI=0 MPICH=1
addons:
  ssh_known_hosts: xgitlab.cels.anl.gov
  
before_install:
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone git@xgitlab.cels.anl.gov:schanen/PIPSThirdPartyLibs.git
  - cp ./PIPSThirdPartyLibs/Cbc-2.9.8.tgz ./ThirdPartyLibs/CBC 
  - cp ./PIPSThirdPartyLibs/metis-4.0.3.tar.gz ./ThirdPartyLibs/METIS
  - cp ./PIPSThirdPartyLibs/solvers.tar.gz ./ThirdPartyLibs/ASL
  - if [ $TEST_WITH_MA27 -eq "0" ]; then cp ./PIPSThirdPartyLibs/ma57-3.9.0.tar.gz ./ThirdPartyLibs/MA57; fi
# travis doesn't let me download openmpi from open-mpi.org
  - if [ $OPENMPI -eq "1" ]; then cp ./PIPSThirdPartyLibs/openmpi-2.1.0.tar.gz .; fi
  - if [ $TEST_WITH_MA27 -eq "1" ]; then cp ./PIPSThirdPartyLibs/ma27-1.0.0.tar.gz ./ThirdPartyLibs/MA27; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y libblas-dev liblapack-dev 
  - if [ $MPICH -eq "1" ]; then sudo apt-get install -y libmpich-dev mpich; fi
# compile openmpi because ubuntu 14.04 openmpi package is outdated
  - if [ $OPENMPI -eq "1" ]; then sudo apt-get install -y gfortran libopenmpi-dev openmpi-bin openmpi-common; fi
  - if [ $OPENMPI -eq "1" ]; then tar xzf openmpi-2.1.0.tar.gz; fi
  - if [ $OPENMPI -eq "1" ]; then cd openmpi-2.1.0; ./configure -q --prefix=$PWD/../local --enable-mpi-cxx --enable-mpi-fortran=no; fi 
  - if [ $OPENMPI -eq "1" ]; then make -j4; fi 
  - if [ $OPENMPI -eq "1" ]; then make install; cd .. ; fi
  - if [ $OPENMPI -eq "1" ]; then export PATH=$PWD/local/bin:$PATH; fi
  
install:
  - ./build_3rdparty.sh $TEST_WITH_MA27 2
  - ./build_pips.sh 2
  
script:
  - cd build
  - make test
